import msal
import requests
import base64
import os
import io
import configparser
import pandas as pd
import tempfile
import subprocess
import sys

print(os.getcwd())
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
config_path = os.path.join(BASE_DIR, "config.cfg")
print(f"Loading configuration from: {config_path}")

config = configparser.ConfigParser()
config.read(config_path)
az = config['azure']

CLIENT_ID = az['CLIENT_ID']
CLIENT_SECRET = az['CLIENT_SECRET']
TENANT_ID = az['TENANT_ID']
MAILBOX = az['MAILBOX']
# DOWNLOAD_DIR = 'downloads'
# OUTPUT_DIR = 'outputs'

GRAPH_ENDPOINT = 'https://graph.microsoft.com'

def get_token():
    app = msal.ConfidentialClientApplication(
        CLIENT_ID,
        authority=f'https://login.microsoftonline.com/{TENANT_ID}',
        client_credential=CLIENT_SECRET
    )
    result = app.acquire_token_for_client(
        scopes=[f'{GRAPH_ENDPOINT}/.default']
    )
    if 'access_token' not in result:
        raise Exception(f'Auth failed: {result.get('error_description')}')
    print('Authentication successful')
    print(f"Token expires in: {result['expires_in']} seconds")
    return result['access_token']

def get_unread_mails(token):
    headers = {'Authorization': f'Bearer {token}'}
    url = (
        f"{GRAPH_ENDPOINT}/v1.0/users/{MAILBOX}/messages"
        f"?$filter=isRead eq false and hasAttachments eq true"
        f"&$select=id,subject,from,hasAttachments,receivedDateTime"
        f"&$top=20"
    )
    r = requests.get(url, headers=headers)
    r.raise_for_status()
    emails = r.json().get("value", [])
    print(f"Found {len(emails)} unread email(s) with attachments.")
    return emails

def get_attachments(token, email_id):
    headers = {'Authorization': f'Bearer {token}'}
    url = f"{GRAPH_ENDPOINT}/v1.0/users/{MAILBOX}/messages/{email_id}/attachments"
    r = requests.get(url, headers=headers)
    r.raise_for_status()
    
    attachments = []
    for att in r.json().get('value', []):
        name = att.get('name', '')
        if not name.upper().endswith(('.CSV', '.XLSX')):
            continue
        
        file_bytes = base64.b64decode(att['contentBytes'])
        buffer = io.BytesIO(file_bytes)
        attachments.append({"name": name, "buffer": buffer})
        print(f'Loaded into memory: {name} ({len(file_bytes)} bytes)')
        
    return attachments

def clean_dataset_in_memory(attachments):
    REQUIRED_FILES = ['DISH-D.CSV', 'CUSTINFO.CSV', 'IREPORT (1).CSV']
    
    found = {req: None for req in REQUIRED_FILES}
    for att in attachments:
        name_upper = att['name'].upper()
        for req in REQUIRED_FILES:
            if req in name_upper:
                found[req] = att
                break
        
    missing = [req for req, val in found.items() if val is None]
    if missing:
        raise ValueError(
            f"Missing required file(s): {', '.join(missing)}. "
            f"Please attach DISH-D.CSV, CUSTINFO.CSV, and IREPORT.CSV in the same email."
        )

    print("  All 3 required files found. Running master report...")
    
    with tempfile.TemporaryDirectory() as tmpdir:
        
        for att in attachments:
            file_path = os.path.join(tmpdir, att['name'])
            with open(file_path, 'wb') as f:
                f.write(att['buffer'].getbuffer())
            print(f"  Saved {att['name']} to {file_path}")

        # Step 3: Run create_master_report.py as a subprocess from the temp dir
        script_path = os.path.join(BASE_DIR, "create_master_report.py")

        result = subprocess.run(
            [sys.executable, script_path],
            cwd=tmpdir,          # script runs inside temp dir, finds the CSVs there
            capture_output=True,
            text=True
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"create_master_report.py failed:\n{result.stderr}"
            )

        print(result.stdout)

        # Step 4: Read the output file into memory
        output_path = os.path.join(tmpdir, "Master_Sales_Report.csv")

        if not os.path.exists(output_path):
            raise FileNotFoundError(
                "Master_Sales_Report.csv was not generated by the script."
            )

        output_buffer = io.BytesIO()
        with open(output_path, "rb") as f:
            output_buffer.write(f.read())
        output_buffer.seek(0)

        print("  Report loaded into memory. Temp files will now be deleted.")

        # Temp directory and all files inside are automatically deleted here

    return "Master_Sales_Report.csv", output_buffer

def reply_with_attachment(token, sender_email, original_subject, filename, buffer):
    headers = {'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'}
    
    encoded = base64.b64encode(buffer.read()).decode('utf-8')
    
    payload = {
        "message": {
            "subject": f"Re: {original_subject} — Cleaned Dataset",
            "body": {
                "contentType": "Text",
                "content": (
                    "Hi,\n\n"
                    "Please find the cleaned dataset attached.\n\n"
                    # "Cleaning steps applied:\n"
                    # "  - Removed blank rows\n"
                    # "  - Removed duplicate entries\n"
                    # "  - Standardised column names\n\n"
                    "Best regards,\n"
                    "Automated Report Service"
                )
            },
            "toRecipients": [
                {"emailAddress": {"address": sender_email}}
            ],
            "attachments": [{
                "@odata.type": "#microsoft.graph.fileAttachment",
                "name": filename,
                "contentBytes": encoded
            }]
        }
    }

    url = f"{GRAPH_ENDPOINT}/v1.0/users/{MAILBOX}/sendMail"
    r = requests.post(url, headers=headers, json=payload)
    r.raise_for_status()
    print(f"  Reply sent to: {sender_email}")
    
def mark_as_read(token, email_id):
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json"
    }
    url = f"{GRAPH_ENDPOINT}/v1.0/users/{MAILBOX}/messages/{email_id}"
    requests.patch(url, headers=headers, json={"isRead": True})
    print("  Marked as read.")
        
def run():
    token = get_token()
    emails = get_unread_mails(token)
    
    if not emails:
        print("No new emails to process.")
        return
    
    for email in emails:
        email_id = email['id']
        subject = email.get('subject', '(No Subject)')
        sender_email = email['from']['emailAddress']['address']
        
        print(f"\nProcessing email from: {sender_email} | Subject: {subject}")
        
        attachments = get_attachments(token, email_id)
        
        if not attachments:
            print("  No valid attachments found. Skipping email.")
            mark_as_read(token, email_id)
            continue
        
        try:
            cleaned_name, output_buffer = clean_dataset_in_memory(attachments)
            reply_with_attachment(token, sender_email, subject, cleaned_name, output_buffer)
        except Exception as e:
            print(f"  Error processing email: {e}")
            
        mark_as_read(token, email_id)
            
if __name__ == "__main__":
    run()
                